# Generated by Django 6.0.1 on 2026-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Boleto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigoEscola", models.CharField(max_length=255)),
                ("codigoAluno", models.IntegerField()),
                ("codigoCarne", models.IntegerField()),
                ("numeroCarne", models.CharField(max_length=255)),
                ("dataVencimento", models.DateTimeField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("multa", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "percentualMulta",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("jurosDia", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "percentualJuro",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("serieTurma", models.CharField(max_length=255)),
                ("statusCobranca", models.IntegerField()),
            ],
        ),
    ]
