# Generated by Django 6.0.1 on 2026-01-21 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Divida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numeroCobranca", models.CharField(max_length=20)),
                ("dataPrimeiraImportacao", models.DateField(blank=True, null=True)),
                ("dataUltimaImportacao", models.DateField(blank=True, null=True)),
                ("agencia", models.CharField(blank=True, max_length=10, null=True)),
                ("conta", models.CharField(blank=True, max_length=50, null=True)),
                ("dataVencimento", models.DateField()),
                ("valorCobranca", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valorCobrancaAcao",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("statusValorAcao", models.BooleanField(blank=True, null=True)),
                ("parcela", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "valorMulta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valorJuro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("dataAcertoMantenedora", models.DateField(blank=True, null=True)),
                (
                    "valorPago",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "numeroContrato",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("statusBolsista", models.BooleanField(blank=True, null=True)),
                ("statusEstornado", models.BooleanField(blank=True, null=True)),
                ("codigoAluno", models.IntegerField(blank=True, null=True)),
                ("nomeAluno", models.CharField(blank=True, max_length=50, null=True)),
                ("serie", models.CharField(blank=True, max_length=50, null=True)),
                ("ano", models.IntegerField(blank=True, null=True)),
                ("dataInicioJuro", models.DateField(blank=True, null=True)),
                ("dataAcertoJw", models.DateField(blank=True, null=True)),
                ("numeroDias", models.IntegerField(blank=True, null=True)),
                ("mesInicioCorrecao", models.IntegerField(blank=True, null=True)),
                ("anoInicioCorrecao", models.IntegerField(blank=True, null=True)),
                (
                    "indiceInicial",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("mesFimCorrecao", models.IntegerField(blank=True, null=True)),
                ("anoFimCorrecao", models.IntegerField(blank=True, null=True)),
                (
                    "indiceFinal",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "valorCorrigido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentualMulta",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "valorMultaJw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentualJuros",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "valorJuroJw",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valorSubtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "percentualHonorarios",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "valorHonorarios",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "valorTotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("statusPagoJw", models.BooleanField(blank=True, null=True)),
                ("dataPagoJw", models.DateField(blank=True, null=True)),
                (
                    "valorCobrado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("numeroRecibo", models.IntegerField(blank=True, null=True)),
                ("dataImpressaoCarta", models.DateField(blank=True, null=True)),
                (
                    "nomeResponsavelCobranca",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("statusAcao", models.BooleanField(blank=True, null=True)),
                ("statusSpcNaoEnviar", models.BooleanField(blank=True, null=True)),
                ("pasta", models.CharField(blank=True, max_length=255, null=True)),
                ("numeroVara", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "numeroProcesso",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("dataAcao", models.DateField(blank=True, null=True)),
                ("statusNaoEnviarCarta", models.BooleanField(blank=True, null=True)),
                ("statusAcordo", models.BooleanField(blank=True, null=True)),
                ("dataResponsavelCobranca", models.DateField(blank=True, null=True)),
                ("dataSpcEnvio", models.DateField(blank=True, null=True)),
                ("statusSpcEnvio", models.TextField(blank=True, null=True)),
                ("dataSpcBaixa", models.DateField(blank=True, null=True)),
                ("statusSpcBaixa", models.TextField(blank=True, null=True)),
                ("statusSpcBaixaManual", models.BooleanField(blank=True, null=True)),
                ("statusSpcBaixar", models.BooleanField(blank=True, null=True)),
                ("remessaSpcEnvio", models.IntegerField(blank=True, null=True)),
                ("remessaSpcBaixa", models.IntegerField(blank=True, null=True)),
                ("dataAcertoJwMantenedora", models.DateField(blank=True, null=True)),
                ("obsJw", models.TextField(blank=True, null=True)),
                (
                    "acordo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.acordo",
                    ),
                ),
                (
                    "alinea",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.alinea",
                    ),
                ),
                (
                    "andamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.andamento",
                    ),
                ),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.banco",
                    ),
                ),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.entidade",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.escola",
                    ),
                ),
                (
                    "lugar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.lugar",
                    ),
                ),
                (
                    "posicaoCheque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.posicaocheque",
                    ),
                ),
                (
                    "posicaoContrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.posicaocontrato",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.responsavel",
                    ),
                ),
                (
                    "responsavelAtual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atual_boletos",
                        to="cobranca.responsavel",
                    ),
                ),
                (
                    "tipoCobranca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.tipocobranca",
                    ),
                ),
            ],
        ),
    ]
