# Generated by Django 6.0.1 on 2026-01-13 18:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0002_boleto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acordo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Alinea",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Banco",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Entidade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=255)),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Escritorio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AcordoParcelas",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vencimento", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_pagamento", models.DateField()),
                (
                    "acordo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acordo_parcelas",
                        to="cobranca.acordo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Escola",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo", models.CharField(max_length=255)),
                ("nome", models.CharField(max_length=255)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("cidade", models.CharField(blank=True, max_length=255, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("cep", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("obs", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolas",
                        to="cobranca.entidade",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="entidade",
            name="escritorio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entidades",
                to="cobranca.escritorio",
            ),
        ),
        migrations.CreateModel(
            name="Andamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="andamentos",
                        to="cobranca.escritorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lugar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lugares",
                        to="cobranca.escritorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosicaoCheque",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posicao_cheques",
                        to="cobranca.escritorio",
                    ),
                ),
            ],
            options={
                "ordering": ("nome",),
            },
        ),
        migrations.CreateModel(
            name="PosicaoContrato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "escritorio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posicao_contratos",
                        to="cobranca.escritorio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cpf", models.CharField(max_length=255)),
                ("nome", models.CharField(max_length=255)),
                ("nascimento", models.DateField(blank=True, null=True)),
                ("endereco", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "complemento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("cidade", models.CharField(blank=True, max_length=255, null=True)),
                ("uf", models.CharField(blank=True, max_length=2, null=True)),
                ("cep", models.CharField(blank=True, max_length=255, null=True)),
                ("rg", models.CharField(blank=True, max_length=255, null=True)),
                ("rg_emissao", models.DateField(blank=True, null=True)),
                (
                    "estado_civil",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("telefones", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "entidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsaveis",
                        to="cobranca.entidade",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="acordo",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acordos",
                to="cobranca.responsavel",
            ),
        ),
    ]
