# Generated by Django 6.0.1 on 2026-02-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0003_alter_divida_acordo_alter_divida_alinea_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Indice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField()),
                ("mes", models.IntegerField()),
                ("indice", models.IntegerField()),
            ],
        ),
    ]
