# Generated by Django 6.0.1 on 2026-02-18 13:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0004_indice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsavelImportacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_escola", models.CharField(max_length=50)),
                ("cpf", models.CharField(max_length=20, unique=True)),
                ("nome", models.CharField(max_length=255)),
                ("rg", models.CharField(max_length=50)),
                ("endereco", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=255)),
                ("cidade", models.CharField(max_length=255)),
                ("uf", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("nacionalidade", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="BoletoImportacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("codigo_carne", models.BigIntegerField()),
                ("codigo_aluno", models.BigIntegerField()),
                ("numero_carne", models.CharField(max_length=100)),
                ("data_vencimento", models.DateTimeField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("multa", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "percentual_multa",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("juros_dia", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "percentual_juro",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("serie_turma", models.CharField(max_length=100)),
                ("status_cobranca", models.IntegerField()),
                ("aluno_nome", models.CharField(max_length=255)),
                ("aluno_genero", models.CharField(max_length=1)),
                ("aluno_data_nascimento", models.DateTimeField()),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boletos",
                        to="cobranca.responsavelimportacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TelefoneImportacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.CharField(max_length=30)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("e_principal", models.BooleanField(default=False)),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="telefones",
                        to="cobranca.responsavelimportacao",
                    ),
                ),
            ],
        ),
    ]
