# Generated by Django 6.0.1 on 2026-02-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0005_responsavelimportacao_boletoimportacao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsavelimportacao",
            name="cpf",
            field=models.CharField(max_length=20),
        ),
    ]
