# Generated by Django 6.0.1 on 2026-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0006_alter_responsavelimportacao_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsavelimportacao",
            name="rg",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
