# Generated by Django 6.0.1 on 2026-02-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0007_alter_responsavelimportacao_rg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indice",
            name="indice",
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
