# Generated by Django 6.0.1 on 2026-03-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0008_alter_indice_indice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsavel",
            name="rg_emissao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
