# Generated by Django 6.0.1 on 2026-03-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0009_alter_responsavel_rg_emissao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divida",
            name="indiceFinal",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="divida",
            name="indiceInicial",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=18, null=True
            ),
        ),
    ]
