# Generated by Django 6.0.1 on 2026-03-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0010_alter_divida_indicefinal_alter_divida_indiceinicial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divida",
            name="indiceFinal",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="divida",
            name="indiceInicial",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
