# Generated by Django 6.0.1 on 2026-03-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0011_alter_divida_indicefinal_alter_divida_indiceinicial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divida",
            name="nomeAluno",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="divida",
            name="nomeResponsavelCobranca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
