# Generated by Django 6.0.1 on 2026-03-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0012_alter_divida_nomealuno_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="divida",
            name="statusCancelado",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
