# Generated by Django 6.0.1 on 2026-03-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0013_divida_statuscancelado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponsavelApi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpf", models.CharField(max_length=100)),
                ("nome", models.CharField(max_length=255)),
                ("rg", models.CharField(max_length=20)),
                ("endereco", models.CharField(max_length=255)),
                ("barrio", models.CharField(max_length=255)),
                ("uf", models.CharField(max_length=2)),
                ("cep", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=100)),
                ("nacionalidade", models.CharField(max_length=50)),
            ],
        ),
    ]
