# Generated by Django 6.0.1 on 2026-03-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0014_responsavelapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsavelapi",
            name="cidade",
            field=models.CharField(default="artur", max_length=255),
            preserve_default=False,
        ),
    ]
