# Generated by Django 6.0.1 on 2026-03-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0015_responsavelapi_cidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="responsavelapi",
            name="barrio",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="cep",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="cidade",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="cpf",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="email",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="endereco",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="nacionalidade",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="nome",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="rg",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="responsavelapi",
            name="uf",
            field=models.CharField(max_length=2, null=True),
        ),
    ]
