# Generated by Django 6.0.1 on 2026-04-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cobranca",
            "0016_alter_responsavelapi_barrio_alter_responsavelapi_cep_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Boleto",
            new_name="BoletoApi",
        ),
    ]
