# Generated by Django 6.0.1 on 2026-04-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0017_rename_boleto_boletoapi"),
    ]

    operations = [
        migrations.AddField(
            model_name="divida",
            name="codigoCobranca",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
