# Generated by Django 6.0.1 on 2026-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0018_divida_codigocobranca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boletoimportacao",
            name="multa",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name="responsavelimportacao",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
