# Generated by Django 6.0.1 on 2026-05-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0019_alter_boletoimportacao_multa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="boletoimportacao",
            name="escola",
            field=models.ForeignKey(
                default=101,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boletos",
                to="cobranca.escola",
            ),
            preserve_default=False,
        ),
    ]
