# Generated by Django 6.0.1 on 2026-05-12 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0020_boletoimportacao_escola"),
    ]

    operations = [
        migrations.AddField(
            model_name="divida",
            name="alterado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="divida",
            name="alterado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dividas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="divida",
            constraint=models.UniqueConstraint(
                fields=("entidade", "numeroCobranca"), name="unique_divida_entidade"
            ),
        ),
    ]
