# Generated by Django 6.0.1 on 2026-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0021_divida_alterado_em_divida_alterado_por_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="divida",
            name="unique_divida_entidade",
        ),
        migrations.AddConstraint(
            model_name="divida",
            constraint=models.UniqueConstraint(
                fields=("entidade", "numeroCobranca"),
                name="unique_entidade_numeroCobranca",
            ),
        ),
    ]
