# Generated by Django 6.0.1 on 2026-05-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0022_remove_divida_unique_divida_entidade_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="responsavel",
            constraint=models.UniqueConstraint(
                fields=("entidade", "cpf"), name="unique_entidade_cpf"
            ),
        ),
    ]
