# Generated by Django 6.0.1 on 2026-05-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0023_responsavel_unique_entidade_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divida",
            name="alterado_em",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
