# Generated by Django 6.0.1 on 2026-05-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0024_alter_divida_alterado_em"),
    ]

    operations = [
        migrations.AddField(
            model_name="responsavel",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
