# Generated by Django 6.0.1 on 2026-05-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0025_responsavel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divida",
            name="codigoCobranca",
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
