# Generated by Django 6.0.1 on 2026-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0026_alter_divida_codigocobranca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="divida",
            name="codigoCobranca",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, unique=True
            ),
        ),
    ]
