# Generated by Django 6.0.1 on 2026-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0027_alter_divida_codigocobranca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acordoparcelas",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
