# Generated by Django 6.0.1 on 2026-06-01 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0028_alter_acordoparcelas_data_pagamento"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AcordoParcelas",
            new_name="AcordoParcela",
        ),
    ]
