# Generated by Django 6.0.1 on 2026-06-02 18:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0029_rename_acordoparcelas_acordoparcela"),
    ]

    operations = [
        migrations.CreateModel(
            name="Baixa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("576948bf-4d50-4534-a592-da04d7770257"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("criado_em", models.DateField(auto_now_add=True)),
                (
                    "divida",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baixas",
                        to="cobranca.divida",
                    ),
                ),
                (
                    "parcela",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baixas",
                        to="cobranca.acordoparcela",
                    ),
                ),
            ],
        ),
    ]
