# Generated by Django 6.0.1 on 2026-06-02 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0030_baixa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baixa",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
