# Generated by Django 6.0.1 on 2026-06-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cobranca", "0031_alter_baixa_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="escritorio",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="escritorio",
            name="endereco",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="escritorio",
            name="fone",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
